### PR TITLE
CenterMarker Rotation Fix + Misc

### LINKED ISSUE #425: Reword Redirected walking feature titlebars (Auto-turn, 'redirected walking' and space turn)
When Auto-turn and redirected walking first debuted, there was a ton of confusion as to which was used for infinite-walk (with people trying redirected walking and not being able to walk very far, when auto-turn is more suited for that). In actuality, all of these features are some implementation of [Redirected Walking](https://en.wikipedia.org/wiki/Redirected_walking) and should have some mention of that. In order to make things less confusing, we ended up adding 'aka infinite walk' to auto-turn's title bar, but it's not quite right and doesn't really follow industry terms.

As discussed in chat, the most agreeable (for the moment) change would be to change the following titlebars from
- Auto-turn (aka infinite walk) Settings
- Redirected walking
- Space-turn

to something like 
- Auto-turn Settings (for discrete redirected walking)
- Vestibular motion (?) (for gradual redirected walking?)
- Space-turn (for manual redirected walking)

More input here, any suggestions/comments?

### LINKED ISSUE #436: Reset All Settings to defaults
As we alter some steamVR settings, optionally it would be nice if we provided users a way via CMD line to reset all their Settings.

This should be able to be easily done via calling `RemoveKeyInSection` for each section.

### LINKED ISSUE #440: Error Behaviour Refactor ovr settings/overlay wrapper
Update Logic to be flat rather than nested series. to improve read-ability.

```cpp
if (error) {
	// Error handling
}
idealThing();
```

instead of 

```cpp
if (noError) {
	idealThing();
}
else {
	// Error handling
}
```

since if additional error handling is necessary the ideal path gets more and more indented and difficult to follow
```cpp
if (noError1) {
	if (noError2) {
		idealThing();
	}
	else {
		// Error handling 2
	}
}
else {
	// Error handling 1
}
```
compared to
```cpp
if (error1) {
	// Error handling
}
if (error2) {
	// Error handling
}
idealThing();
```

### LINKED ISSUE #446: Force Chaperone Walls to be visible for WMR users.
For some reason WMR disables the default chaperone walls in SteamVR.  Presumably because they want to use their own "Boundaries".  The WMR boundary wall difficult to see where the chaperone grid would have help you away from danger.    It would be great to have an option to re-enable or force the chaperone walls to show for WMR users.   All other settings of OVAS work, ie. audible warning, vibration all properly activate when passing the steamvr chaperone, however the Wall does not show.

Please consider this feature in a future version if its possible.  

ps. Thanks again for this amazing tool, its made things much easier for WMR users.   Sometimes steamvr will rotate the playspace, and you have no ability to save a new one, creating a preset for offsets in OVRAS has made a huge difference.  First time i pop into steamVR, i load up the preset, and everything is right again :)

### LINKED ISSUE #452: Center Marker does not follow Space Turn movement
**Describe the bug**
When using space turn the center marker will move further and further away from the center of the play space. 

**To Reproduce**
Enable the Center Marker and use space turn to rotate the play space, as you move further out from the center of the spacer the marker will move in a wider circle with the turn. 

I have tested this with a fresh config ini

**Expected behavior**
Marker should stay in the center of the play space. 

**Software (please complete the following information):**
 - OS:  Windows 10 1809
 - Advanced Settings Version: 5.1.0

**Hardware (please complete the following information):**
 - CPU: i7-8700
 - Graphics Card: RTX 2070
 - HMD: Index

### LINKED ISSUE #457: Update OpenGL rendering GPU information
instructions unclear need to update.

### PR DESCRIPTION
**Pull request by ykeara**
fixes #452 
fixes #440 
fixes #436 
fixes #425
fixes #457
fixes #446 

### New Feature
- add Ability in `Settings` to force you to use SteamVR's Chaperone (VERY EXPERIMENTAL)
- Added Ability to reset all [steamvr] Settings via `--reset-steamvr-settings` as launch param.

### TODO
Marked Some Errors in saved settings, but adjusting them might be a breaking change so leaving for now.

### Documentation Update

Updated Common Issues about OpenGL rendering issues to be more clear and step-by-step

### Refactor

- changed error handling in wrapper classes to be easier to read.
- Re-worded Rotation Features to make more logical sense
- Added a Scroll View to the settings tab to prevent possible over-run

### Bug Fixes

- fixed a qml issue with Center Marker (legacy) btn.
- fixed new center marker to properly follow you while using rotation features.

### CODE REVIEW

File: src/tabcontrollers/MoveCenterTabController.cpp [hunk 1]
```diff
@@ -2715,6 +2722,53 @@ void MoveCenterTabController::updateSpace( bool forceUpdate )
             }
         }
 
+        // Center Marker for playspace.
+        if ( m_centerMarkerUpdate )
```
Comment (ykeara) [inline src/tabcontrollers/MoveCenterTabController.cpp:2726]: @Kung-vr  Un-sure about proper verbage here (i.e. raw/un-rotated/??) if you could have a look

File: src/tabcontrollers/MoveCenterTabController.cpp [hunk 2]
```diff
@@ -2722,6 +2722,53 @@ void MoveCenterTabController::updateSpace( bool forceUpdate )
...
+            universePlayCenterTempCoords[0]
+                -= offsetUniverseCenter.m[0][3]
+                   - m_universeCenterForReset.m[0][3];
+            universePlayCenterTempCoords[1]
+                -= offsetUniverseCenter.m[1][3]
+                   - m_universeCenterForReset.m[1][3];
+            universePlayCenterTempCoords[2]
+                -= offsetUniverseCenter.m[2][3]
+                   - m_universeCenterForReset.m[2][3];
+            // Rotate un-rotated to raw?
```
Comment (Kung-vr) [inline src/tabcontrollers/MoveCenterTabController.cpp:2745]: Only comment is terminology here. We've been calling what you're referring to here as "rotated" coordinates. They're the current coordinates most things that reference the universe center will actually deal with. They're relative to the universe center that SteamVR sees, (the one we have adjusted to the user-set rotation offset). It might get a little redundant though to say that here "// Rotate un-rotated to rotated"? I don't know. But they're not raw coordinates. The Raw coordinates z axis will align with the pointing direction of the master lighthouse usually. The rotated coordinates z axis will align with the forward direction presented to games by our rotated universe center. (And un-rotated coordinates z axis should align with our physical room's original room setup "playspace forward" direction.)

File: src/res/qml/SettingsPage.qml [hunk 3]
```diff
@@ -68,6 +68,13 @@ MyStackViewPage {
                 OverlayController.setDisableVersionCheck(checked, true)
             }
         }
+        MyToggleButton {
+            id: nativeChaperoneToggleButton
+            text: "Driver Bounds Import (un-checked to force use Steam's native chaperone)"
```
Comment (Kung-vr) [inline src/res/qml/SettingsPage.qml:73]: Whenever I've been adding settings to the settings tab, I've been sort of passively using the style that unchecked = default (without explicitly communicating this in docs or to the user). That's the case though for most of the other settings in there, so might want to consider making unchecked be default driver bounds, and checked be "Force SteamVR's Native Chaperone" that could help get of the parenthetical in the setting description too.

Comment (ykeara) [reply src/res/qml/SettingsPage.qml:73]: Yea Before a Real release I need to make some sub-pages here...we have too many settings, so I can change that...a dn change wording.

File: src/tabcontrollers/MoveCenterTabController.cpp (hunk 2 above)
Comment (ykeara) [reply src/tabcontrollers/MoveCenterTabController.cpp:2745]: Kk updated on my end, will push it with a later updated.... unrotated to rotated might be silly but it works..

**Comment by ykeara** [comment]
Closing PR for now Ran into some issues.... fixing things will re-open when I have fix up

File: src/openvr/ovr_settings_wrapper.cpp [hunk 4]
```diff
@@ -145,4 +145,15 @@ SettingsError removeKeyInSection( std::string section,
     return handleErrors( settingsKey, error, customErrorMsg );
 }
 
+void resetAllSettings()
+{
+    // these should cover all sections we touch and should be added to if we
+    // touch more or they change
+    removeSection( vr::k_pch_SteamVR_Section, "While Reseting All" );
```
Comment (username223) [inline src/openvr/ovr_settings_wrapper.cpp:152]: `Resetting` has two `t`s. :)

File: src/settings/internal/settings_controller.h [hunk 5]
```diff
@@ -426,18 +426,22 @@ class SettingsController
                             QtInfo{ "colorBlueNew" },
                             1.0 },
 
+        // TODO BUG should be in Chaperone Settings Not Video breaking?
```
Comment (username223) [inline src/settings/internal/settings_controller.h:429]: Yes, it is a breaking change.

Maybe we don't even need to use categories at all, just have everything together?

No real reason to change it unless we break the settings in a major way anyway.

File: src/tabcontrollers/ChaperoneTabController.h [hunk 6]
```diff
@@ -412,6 +413,7 @@ class ChaperoneTabController : public QObject
     int chaperoneColorA() const;
 
     bool centerMarkerNew();
+    bool m_overlayNeedsUpdate = false;
```
Comment (username223) [inline src/tabcontrollers/ChaperoneTabController.h:416]: Specify which overlay needs update?

File: src/tabcontrollers/ChaperoneTabController.h [hunk 7]
```diff
@@ -377,12 +377,11 @@ class ChaperoneTabController : public QObject
 
     std::string m_floorMarkerFN = "/res/img/chaperone/centermark.png";
     void initFloorOverlay();
-    void updateOverlay();
     void updateOverlayColor();
     void checkOverlayRotation();
     int m_rotationUpdateCounter = 0;
     int m_rotationCurrent = 0;
-    bool m_overlayNeedsUpdate = false;
+    bool m_overlayIsInit = false;
```
Comment (username223) [inline src/tabcontrollers/ChaperoneTabController.h:384]: Specify which overlay is init'd?

File: src/settings/internal/settings_controller.h (hunk 5 above)
Comment (ykeara) [reply src/settings/internal/settings_controller.h:429]: Yea I'll change the comments a bit here, but leave them so hopefully next time we do a breaking we can correct them (if code is relevant)

**Comment by ykeara** [comment]
Re-named

initFloorOverlay()-> initCenterMarkerOverlay()
updateOverlay()-> updateCenterMarkerOverlay()
updateOverlayColor()->updateCenterMarkerOverlayColor()

m_overlayNeedsUpdate -> m_centerMarkerOverlayNeedsUpdate
m_overlayIsInit -> m_centerMarkerOverlayIsInit
m_checkOverlayRotation()->checkCenterMarkerOverlayRotationCount()

clarified settings location error, and better marked for fix @ breaking change
corrected spelling of resetting

**Comment by username223** [comment]
Not tested in VR.
Don't know if @Kung-vr still has any points though.

File: src/res/qml/SettingsPage.qml [hunk 8]
```diff
@@ -75,7 +75,7 @@ MyStackViewPage {
             }
             MyToggleButton {
                 id: nativeChaperoneToggleButton
-                text: "Driver Bounds Import (un-checked to force use Steam's native chaperone)"
+                text: "Force Use Steam's Chaperone (experimental + requires restart of SteamVR)"
```
Comment (Kung-vr) [inline src/res/qml/SettingsPage.qml:78]:
```suggestion
                text: "Force Use SteamVR Chaperone (experimental + SteamVR restart required)"
```
Thanks for switching the default. Just a little terminology suggestion (SteamVR vs Steam) and trying to shorten the line a bit
