### PR TITLE
Fixed Manifest Behavor

### LINKED ISSUE #196: Manifest Not un-installing/re-installing correctly
If you have an old path (pre 3.0.0) manifest it does not seem to un-install w/ --force-remove-manifest.

Can manually delete it in steam/config/appconfig.json

### PR DESCRIPTION
**Pull request by ykeara**
Fixes #196 

Some things Addressed.

force-install-manifest and remove will now remove the Manifest Key From SteamVR even if it was installed in a different directory.

fixed a bug where the re-install was referencing the current dir rather than the installed DIR
fixed a bug where native separators were not properly applied....

Added extensive logging, and helpful messages in log in case it errors out somehow.

Did not test on linux, and it will need to be tested?

Code could be cleaned up a bit, but I left as-is  so it will be easier to possibly in the future include an install and a remove option.... that are not quite as aggressive. (i.e. stay in their own directory)

Hopefully this should address some of the installer not working issues.

### CODE REVIEW

File: src/utils/setup.cpp [hunk 1]
```diff
@@ -117,15 +117,30 @@ void enableApplicationAutostart()
...
-        throw std::runtime_error(
-            std::string( "Could not add application manifest: " )
-            + std::string(
-                vr::VRApplications()->GetApplicationsErrorNameFromEnum(
-                    app_error ) ) );
+        LOG( ERROR ) << "Manifest Is already Installed for Key "
+                     << application_strings::applicationKey;
+        LOG( ERROR ) << "You may have installed Advanced Settings in another "
+                        "directory please remove it OR"
+                        "OR manually delete the manifest install in in Steam "
```
Comment (username223) [inline src/utils/setup.cpp]: On the line above there is another OR leading to the final string being "[..] directory please remove it OROR manually delete [..]".

Comment (ykeara) [reply src/utils/setup.cpp]: done good catch.
