### PR TITLE
Keyboard Parse Fix

### LINKED ISSUE #465: Alt-Tab no Up Key Event
**Describe the bug**
Using Alt-Tab, alt key does not appear to get the key-up event causing moderate problems.

As reported via Steam Community Forums

### PR DESCRIPTION
**Pull request by ykeara**
fixes #465 

- Updates OVR to 1.12.5
- Fixes an Error With Keyboard parsing sometimes not hitting the "up" keystroke
- Adds Oculus block API setting  very experimental? needs testing.

### CODE REVIEW

File: src/tabcontrollers/SettingsTabController.cpp [hunk 1]
```diff
@@ -52,6 +53,20 @@ bool SettingsTabController::nativeChaperoneToggle()
     return m_nativeChaperoneToggle;
 }
 
+bool SettingsTabController::oculusSdkToggle()
+{
+    std::pair<ovr_settings_wrapper::SettingsError, bool> p
```
Comment (username223) [inline src/tabcontrollers/SettingsTabController.cpp:58]: Would prefer using `auto` here instead of the type, in case we want to change it later.

File: src/tabcontrollers/SettingsTabController.cpp [hunk 2]
```diff
@@ -70,6 +85,24 @@ void SettingsTabController::setNativeChaperoneToggle( bool value, bool notify )
     }
 }
 
+void SettingsTabController::setOculusSdkToggle( bool value, bool notify )
+{
+    if ( m_oculusSdkToggle != value )
```
Comment (username223) [inline src/tabcontrollers/SettingsTabController.cpp:90]: Would prefer using the externally visible `oculusSdkToggle()` because it'll be easier if we need to change something later.

**Comment by ykeara** [comment]
merged travis completed build, but didn't update github?
