### PR TITLE
Refactor main.cpp, remove easylogging++ command line args, fix desktop width not being saved

### LINKED ISSUE #52: SteamVr overlay Width Save state
Add a save state to steamvroverlay width setting.

### LINKED ISSUE #62: Log message about being unable to find overlay "valve.steam.desktop": VROverlayError_UnknownOverlay
Upon starting the application the following message is logged:

```
[INFO] 2019-01-23 18:38:15: Could not find overlay "valve.steam.desktop": VROverlayError_UnknownOverlay
```

It is very likely to stem from this

```cpp
auto error = vr::VROverlay()->FindOverlay( steamDesktopOverlaykey,
                                           &pOverlayHandle );
if ( error != vr::VROverlayError_None )
{
    m_steamDesktopOverlayAvailable = false;
    LOG( INFO ) << "Could not find overlay \"" << steamDesktopOverlaykey
                << "\": "
                << vr::VROverlay()->GetOverlayErrorNameFromEnum( error );
}
```

from `src/tabcontrollers/UtilitiesTabController.cpp` on lines `37-43`.

It is unknown when this message started appearing and why.

### LINKED ISSUE #63: Deprecate and remove user ability to changing logging settings
Currently, the user is able to change the settings of the logger by putting a `logger.conf` file in the executable directory.

Since the logs are mostly a developer tool for troubleshooting it should not fall on the user to make the logs correctly reflect application actions, or to change logging behavior that could make it more difficult for developers to troubleshoot.

Since this is an open source utility, advanced users can always compile from source if they want.

### PR DESCRIPTION
**Pull request by username223**
## This PR:
* Refactors `main.cpp` into `setup.h` and `setup.cpp`.
* Moves the `openvr` files into an `openvr` directory.
* Fixes #63 (Removes the possibility of loading a custom logging file).
* Fixes #52 (the SteamVR Desktop Overlay is loaded after our overlay, simply waits up to 7 seconds for the desktop overlay to initialize).
* Fixes #62 (a result of the above).

## Noteworthy Items:
* Because of the desktop overlay not being deterministically loaded this patch introduces a possible initialization delay in the `UtilityTabController` of up to 7 seconds. On my machine the desktop overlay seems to be available after 2-3 seconds.

## Technical Considerations:
* A thread sleep solution was chosen for the desktop overlay instead of an `async` call in order to simplify code and have imperative initialization as well as simplifying the performance profile. SteamVR and the advanced settings GUI are still responsive.

### CODE REVIEW

File: src/utils/setup.cpp [hunk 1]
```diff
@@ -0,0 +1,299 @@
...
+    conf.set( Level::Debug, ConfigurationType::Enabled, confDisabled );
+
+    // This places the log file in
+    // Roaming/AppData/matzman666/OpenVRAdvancedSettings/AdvancedSettings.log.
+    // The log file placement has been broken since at least git tag "v2.7".
+    // It was being placed in the working dir of the executable.
+    // The change hasn't been documented anywhere, so it is likely that it was
+    // unintentional. This fixes the probable regression until a new path is
+    // decided on.
+    constexpr auto appDataFolders = "/matzman666/OpenVRAdvancedSettings";
```
Comment (ykeara) [inline src/utils/setup.cpp]: Just don't want to forget about this hard-coded directory. Here for Notation mainly.
